### ISSUE TITLE
folda and mapa use '[' command -- slow...

### ISSUE THREAD

**Issue by mathlover2** [Tarrasch/zsh-functional#18]
I noticed that in `folda` and `mapa`, the command `$[` is used instead of the native `$(( ... ))` expressions used by zsh. Changing this improved speed for me dramatically. 

Is there some reason for this, or is the use of `$[` merely a mistake?

**Comment by mathlover2** [comment]
Never mind...It seems that there is no improvement after all.
Closing this.

**Comment by Tarrasch** [comment]
Hmm. Not sure why I choose `$[]` over `$(())` syntax. :)
